hook.Add( "PopulateToolMenu", "CSOSettingsMenu", function()
	spawnmenu.AddToolMenuOption( "Utilities", "TFA SWEP Base Settings", "TFA CS:O", "TFA CS:O", "", "", function( panel )
		panel:ClearControls()
		panel:NumSlider( "Default is 15.", "sv_tfa_cso_dmg_windrider_rb", 1, 250 )
		panel:ControlHelp( "Dual Beretta Windrider's right-click damage." )
		panel:NumSlider( "Default is 20.", "sv_tfa_cso_dmg_gunslinger_rb", 1, 250 )
		panel:ControlHelp( "Dual Beretta Gunslinger's right-click damage." )
		panel:NumSlider( "Default is 25.", "sv_tfa_cso_dmg_gunslinger_gs_rb", 1, 250 )
		panel:ControlHelp( "Dual Beretta Gunslinger GS's right-click damage." )

		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_gunslingers_player", 0, 1 )
		panel:ControlHelp( "Can Dual Beretta Gunslingers deal right-click damage to players?" )
		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_trinity_detect_player", 0, 1 )
		panel:ControlHelp( "Will the Trinity Grenades do special things to players (detect, ignite)?" )
		
		panel:NumSlider( "Default is 65.", "sv_tfa_cso_budgetsword_skill_damage", 1, 250 )
		panel:ControlHelp( "Dual Sword Hellfire's special combo damage, per tick." )
		panel:NumSlider( "Default is 70.", "sv_tfa_cso_dualsword_skill_damage", 1, 250 )
		panel:ControlHelp( "Dual Sword Phantom Slayer's special combo damage, per tick." )
		panel:NumSlider( "Default is 80.", "sv_tfa_cso_dualsword_rb_skill_damage", 1, 250 )
		panel:ControlHelp( "Dual Sword Rainbow Caster's special combo damage, per tick." )
		panel:NumSlider( "Default is 50.", "sv_tfa_cso_hauteclere_damage", 1, 250 )
		panel:ControlHelp( "Hauteclere's combo damage, per sword." )
		
		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_jetgun_player", 0, 1 )
		panel:ControlHelp( "Can Lightning Fury deal radius damage to players?" )
		
		panel:NumSlider( "Default is 450.", "sv_tfa_cso_dmg_arbalest", 1, 4500 )
		panel:ControlHelp( "Arbalest's area damage (right-click)." )
		panel:CheckBox( "Default is off.", "sv_tfa_cso_dmg_arbalest_player", 0, 1 )
		panel:ControlHelp( "Can Arbalest deal area damage (right-click) to players?" )
		
		panel:NumSlider( "Default is 3072.", "sv_tfa_cso_bunkerbuster_place_height", 256, 102400 )
		panel:ControlHelp( "Bunker Buster Plane Height Level" )

		panel:CheckBox( "Default is on.", "sv_tfa_cso_supplybox_spawn_snd", 0, 1 )
		panel:ControlHelp( "Enable supply box spawning sounds?" )
		panel:CheckBox( "Default is on.", "sv_tfa_cso_c4_radio_snd", 0, 1 )
		panel:ControlHelp( "Enable C4 radio sounds?" )
		panel:NumSlider( "Default is 35.", "sv_tfa_cso_c4_timer", 20, 60 )
		panel:ControlHelp( "How many seconds does it take before C4 explodes?" )
		panel:NumSlider( "Default is 10.", "sv_tfa_cso_c4_defuse_time", 5, 15 )
		panel:ControlHelp( "How much seconds it takes to defuse C4?" )
		panel:CheckBox( "Default is off.", "sv_tfa_cso_drop_stuff_on_death", 0, 1 )
		panel:ControlHelp( "Enable drop C4 and Defuse Kit on death?" )
	end )
end )