ENT.Base 			= "npc_vj_zss_zombie1"
ENT.Type 			= "ai"
ENT.PrintName 		= "Mini Zombie Boss"
ENT.Author 			= "DrVrej"
ENT.Contact 		= "http://steamcommunity.com/groups/vrejgaming"
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Zombies"