ENT.Base 				= "npc_vj_creature_base"
ENT.Type 				= "ai"
ENT.PrintName 			= "Horror"
ENT.Author 				= "Mayhem"
ENT.Contact 			= "http://vrejgaming.webs.com/"
ENT.Purpose 			= "Let it eat you."
ENT.Instructions		= "Click on it to spawn it."
ENT.Category			= "Nightmare"
